extends RefCounted

class_name BuildingConstants


const BUILDING_ROAD_OFFSET = 30.0
const BUILDING_CONNECTION_OFFSET = 30.0
const BUILDING_CONNECTION_CURVATURE = 0.65


const BUILDING_SOFT_ENTRY_BLOCKADE_TIME = 5.0 # seconds
const BUILDING_SYMPATHY_WITHOUT_BENEFIT_TIMEOUT = 10.0 # seconds
const BUILDING_MAX_ENTERING_VEHICLE_BLOCKADE_TIME = 50.0 # seconds
const BUILDING_VEHICLE_LEFT_PREMISE_PROGRESS_THRESHOLD = 10.0 # percent
const BUILDING_MAX_LEAVING_VEHICLE_BLOCKADE_TIME = 20.0 # seconds