class_name MapEditorConstants

const MAP_PICKABLE_LAYER_ID = (1 << 4)
const MAP_COLLISION_LAYER_ID = (1 << 5)
const MAP_ALL_DETECTABLE_LAYERS = MAP_PICKABLE_LAYER_ID | MAP_COLLISION_LAYER_ID

const MAP_SNAPPING_RADIUS = 90.0

const SKELETON_DEFAULT_COLOR = Color(0.114, 0.353, 1.0, 0.714)
const SKELETON_ERROR_COLOR = Color(1.0, 0.0, 0.0, 0.714)
const SKELETON_SIZE = 60.0
const SKELETON_SEGMENT_GAP_SIZE = 15.0
const SKELETON_SEGMENT_DASH_SIZE = 30.0
const SKELETON_SEGMENT_WIDTH = 4.0
