class_name RLConstants

const RL_MINUTES_BETWEEN_ACTIONS = 3
const RL_ACTION_REPEAT_REAL_SECONDS = (
	RL_MINUTES_BETWEEN_ACTIONS
	* SimulationConstants.SIMULATION_REAL_SECONDS_PER_IN_GAME_MINUTE
	/ SimulationConstants.SPEED_TURBO_PROCESS_MULTIPLIER
)
const RL_ACTION_REPEAT_FRAMES = max(
	1,
	int(round(RL_ACTION_REPEAT_REAL_SECONDS * SimulationConstants.SPEED_TURBO_PHYSICS_TICKS_PER_SECOND)),
)

const RL_EPISODE_STEP_COUNT = 24 * 60.0 / RL_MINUTES_BETWEEN_ACTIONS

const RL_RESET_AFTER_STEPS = int(RL_EPISODE_STEP_COUNT * RL_ACTION_REPEAT_FRAMES)
