class_name SimulationConstants

const SIMULATION_REAL_SECONDS_PER_IN_GAME_MINUTE = 18.0
const SIMULATION_LIGHTS_ON_THRESHOLD = 19.0 / 24.0
const SIMULATION_LIGHTS_OFF_THRESHOLD = 6.0 / 24.0
const VEHICLE_HEADLIGHTS_STATE_CHANGE_TICKS_VARIANCE = 10
const VEHICLE_BLINKERS_STATE_CHANGE_TICKS_OFFSET = 0.5
const AVERAGE_BUS_SPEED = 25.0
const MAX_INSIDE_BUILDING_SPEED = 45.0
const SIMULATION_WORLD_TO_GAME_UNITS_RATIO = 0.05

const SPEED_1_PROCESS_MULTIPLIER = 1.0
const SPEED_1_PHYSICS_TICKS_PER_SECOND = 60

const SPEED_2_PROCESS_MULTIPLIER = 5.0
const SPEED_2_PHYSICS_TICKS_PER_SECOND = 60

const SPEED_3_PROCESS_MULTIPLIER = 10.0
const SPEED_3_PHYSICS_TICKS_PER_SECOND = 120

const SPEED_TURBO_PROCESS_MULTIPLIER = 20.0
const SPEED_TURBO_PHYSICS_TICKS_PER_SECOND = 180
