class_name SimulationConstants

const SIMULATION_REAL_SECONDS_PER_IN_GAME_MINUTE = 18.0
const SIMULATION_LIGHTS_ON_THRESHOLD = 19.0 / 24.0
const SIMULATION_LIGHTS_OFF_THRESHOLD = 6.0 / 24.0
const VEHICLE_HEADLIGHTS_STATE_CHANGE_TICKS_VARIANCE = 10
const AVERAGE_BUS_SPEED = 25.0
const MAX_INSIDE_BUILDING_SPEED = 45.0
const BUS_OCCUPY_PERON_THRESHOLD = 3 # in-game minutes
const BUS_BOARDING_TIME_PER_PASSENGER = 0.1 # real seconds
const BUS_MAX_BOARDING_TIME = SIMULATION_REAL_SECONDS_PER_IN_GAME_MINUTE * 1.0 # 1 in-game minute
const SIMULATION_WORLD_TO_GAME_UNITS_RATIO = 0.05
const BUS_DEFAULT_COLOR = Color(0.105, 0.514, 0.833)
