class_name SimulationConstants

const SIMULATION_REAL_SECONDS_PER_IN_GAME_MINUTE = 5.0
const SIMULATION_LIGHTS_ON_THRESHOLD = 19.0 / 24.0
const SIMULATION_LIGHTS_OFF_THRESHOLD = 6.0 / 24.0
const VEHICLE_HEADLIGHTS_STATE_CHANGE_TICKS_VARIANCE = 10
const AVERAGE_BUS_SPEED = 25.0
const MAX_INSIDE_BUILDING_SPEED = 30.0
const SIMULATION_WORLD_TO_GAME_UNITS_RATIO = 0.01
