extends RefCounted

class_name CarAI

func get_constants() -> Dictionary:
	return {
		"ACCELERATION": 50.0,
		"DEFAULT_BRAKING": 50.0,
		"EMERGENCY_BRAKING": 150.0,
		"CLOSE_BRAKING": 60.0,
		"CLOSE_BRAKING_LOW_SPEED_THRESHOLD": 20.0,
		"MEDIUM_BRAKING": 120.0,
		"LIGHT_BRAKING": 80.0,
		"MAX_SPEED": 120.0,
		"INTERSECTION_SLOWDOWN_THRESHOLD": 200.0,
		"INTERSECTION_SLOWDOWN": 80.0,
		"BUILDING_ENTRY_SPEED": 40.0,
		"EMERGENCY_STOP_SPEED_MODIFIER": 0.5,
		"MEDIUM_CASTER_SPEED_MODIFIER": 0.3,
		"MEDIUM_CASTER_MIN_SPEED": 1,
		"LONG_CASTER_SPEED_MODIFIER": 0.4,
		"LONG_CASTER_MIN_SPEED": 5,
		"TURN_CRAWL_SPEED": 10.0,
		"REROUTE_THRESHOLD": 10.0,
		"REROUTE_CHANCE": 0.5
	}