class_name ChallengeEnums

enum ScoreReason {
	BUS_INVALID_STATE_FOR_ACTION,
	BUS_ALREADY_IN_RESERVE_SAME_TERMINAL,
	BUS_CHANGED_STATE_WITH_PASSENGERS_ONBOARD,
	BUS_REGULAR_UPKEEP_COST,
	BUS_ARTICULATED_UPKEEP_COST,
	UNSERVED_BRIGADE,
	BORED_PASSENGER,
	SERVICED_PASSENGER,
	SERVICED_STOP_AHEAD_OF_TIME,
	SERVICED_STOP_ON_TIME,
	SERVICED_STOP_SLIGHTLY_LATE,
	SERVICED_STOP_LATE,
	SERVICED_STOP_VERY_LATE,
	LEFT_PASSENGERS_BEHIND,
}

enum ArrivalTimeThreshold {
	SLIGHTLY_LATE = 0,
	LATE = 5,
	VERY_LATE = 10,
}
